import crypto from 'crypto'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { decodeInvoiceToken, generateInvoiceToken } from '@/lib/invoice-tokens'

const OLD_SECRET = process.env.INVOICE_TOKEN_SECRET

function legacyToken(invoiceId: string, timestamp: number, secret: string) {
  const hash = crypto
    .createHash('sha256')
    .update(`${invoiceId}:${timestamp}:${secret}`)
    .digest('hex')
    .substring(0, 16)
  return Buffer.from(`${invoiceId}:${timestamp}:${hash}`).toString('base64url')
}

beforeEach(() => {
  process.env.INVOICE_TOKEN_SECRET = 'invoice-token-test-secret'
  vi.useFakeTimers()
  vi.setSystemTime(new Date('2026-01-01T00:00:00Z'))
})

afterEach(() => {
  if (OLD_SECRET === undefined) delete process.env.INVOICE_TOKEN_SECRET
  else process.env.INVOICE_TOKEN_SECRET = OLD_SECRET
  vi.useRealTimers()
})

describe('invoice tokens', () => {
  it('decodes a valid token generated by the app', () => {
    const token = generateInvoiceToken('inv_123')
    expect(decodeInvoiceToken(token)).toBe('inv_123')
  })

  it('rejects a tampered hash using the timing-safe comparison path', () => {
    const timestamp = Date.now()
    const token = legacyToken('inv_123', timestamp, process.env.INVOICE_TOKEN_SECRET!)
    const decoded = Buffer.from(token, 'base64url').toString('utf8')
    const [invoiceId, issuedAt] = decoded.split(':')
    const tampered = Buffer.from(`${invoiceId}:${issuedAt}:deadbeef`, 'utf8').toString('base64url')

    expect(decodeInvoiceToken(tampered)).toBeNull()
  })

  it('rejects malformed and future timestamps', () => {
    const secret = process.env.INVOICE_TOKEN_SECRET!
    const malformed = legacyToken('inv_123', Number.NaN, secret)
    const future = legacyToken('inv_123', Date.now() + 60_000, secret)

    expect(decodeInvoiceToken(malformed)).toBeNull()
    expect(decodeInvoiceToken(future)).toBeNull()
  })

  /**
   * How long a client's invoice link stays usable.
   *
   * Untested until now, and it is the only limit on a link's life: there is no
   * revocation, nothing is stored, and the sole kill switch is rotating
   * INVOICE_TOKEN_SECRET, which breaks every client's link at once. A silent
   * change here either makes links permanent or kills them early, and nobody
   * would notice until a client complained.
   */
  describe('the one-year lifetime', () => {
    const DAY = 86_400_000
    const at = (ageMs: number) =>
      decodeInvoiceToken(legacyToken('inv_123', Date.now() - ageMs, 'invoice-token-test-secret'))

    it('accepts a link for a year', () => {
      expect(at(0)).toBe('inv_123')
      expect(at(180 * DAY)).toBe('inv_123')
      expect(at(364 * DAY)).toBe('inv_123')
    })

    it('stops accepting it after a year', () => {
      expect(at(366 * DAY)).toBeNull()
      expect(at(730 * DAY)).toBeNull()
    })

    it('rejects a link whose invoice id was swapped for another', () => {
      // The signature covers the id, so a valid link for one invoice cannot be
      // pointed at a different one.
      const token = generateInvoiceToken('inv_123')
      const [, issuedAt, hash] = Buffer.from(token, 'base64url').toString('utf-8').split(':')
      const swapped = Buffer.from(`inv_other:${issuedAt}:${hash}`).toString('base64url')
      expect(decodeInvoiceToken(swapped)).toBeNull()
    })
  })
})
