import crypto from 'crypto'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { decodeInvoiceToken, generateInvoiceToken } from '@/lib/invoice-tokens'

const OLD_SECRET = process.env.INVOICE_TOKEN_SECRET

function legacyToken(invoiceId: string, timestamp: number, secret: string) {
  const hash = crypto
    .createHash('sha256')
    .update(`${invoiceId}:${timestamp}:${secret}`)
    .digest('hex')
    .substring(0, 16)
  return Buffer.from(`${invoiceId}:${timestamp}:${hash}`).toString('base64url')
}

beforeEach(() => {
  process.env.INVOICE_TOKEN_SECRET = 'invoice-token-test-secret'
  vi.useFakeTimers()
  vi.setSystemTime(new Date('2026-01-01T00:00:00Z'))
})

afterEach(() => {
  if (OLD_SECRET === undefined) delete process.env.INVOICE_TOKEN_SECRET
  else process.env.INVOICE_TOKEN_SECRET = OLD_SECRET
  vi.useRealTimers()
})

describe('invoice tokens', () => {
  it('decodes a valid token generated by the app', () => {
    const token = generateInvoiceToken('inv_123')
    expect(decodeInvoiceToken(token)).toBe('inv_123')
  })

  it('rejects a tampered hash using the timing-safe comparison path', () => {
    const timestamp = Date.now()
    const token = legacyToken('inv_123', timestamp, process.env.INVOICE_TOKEN_SECRET!)
    const decoded = Buffer.from(token, 'base64url').toString('utf8')
    const [invoiceId, issuedAt] = decoded.split(':')
    const tampered = Buffer.from(`${invoiceId}:${issuedAt}:deadbeef`, 'utf8').toString('base64url')

    expect(decodeInvoiceToken(tampered)).toBeNull()
  })

  it('rejects malformed and future timestamps', () => {
    const secret = process.env.INVOICE_TOKEN_SECRET!
    const malformed = legacyToken('inv_123', Number.NaN, secret)
    const future = legacyToken('inv_123', Date.now() + 60_000, secret)

    expect(decodeInvoiceToken(malformed)).toBeNull()
    expect(decodeInvoiceToken(future)).toBeNull()
  })
})
