ALTER TABLE "invoice_logo_settings"
ADD COLUMN IF NOT EXISTS "logoData" BYTEA,
ADD COLUMN IF NOT EXISTS "logoMimeType" TEXT,
ADD COLUMN IF NOT EXISTS "logoFileName" TEXT,
ADD COLUMN IF NOT EXISTS "logoSize" INTEGER;
