/**
 * Did the email actually leave the building?
 *
 * An invoice may only be stamped SENT when a message really went out. Getting
 * this wrong is expensive in a way that hides: the invoice reads SENT, it drops
 * off the review queue, nobody chases it, and the client never received
 * anything. Unpaid work that nobody is looking for.
 *
 * It went wrong because the gate had two sources of truth. The send routes read
 * `ALLOW_REAL_CLIENT_EMAILS` / `ENABLE_EMAIL_SENDING` from the environment,
 * while `sendEmail()` reads the EmailSettings row that Settings → Email writes.
 * With the env flags on and sending paused in Settings, `sendEmail` returned
 * `{ success: true, warning: 'SENDING_DISABLED' }` and the route, seeing only
 * `success`, marked the invoice SENT.
 *
 * So "success" is not the question. This is.
 *
 * Pure: no Prisma, no env, no clock.
 */

export type SendOutcome =
  /** A real message was accepted by the provider. */
  | "DELIVERED"
  /** Deliberately not sent · test mode, or sending paused in Settings. */
  | "HELD"
  /** Tried and failed. */
  | "FAILED"

export interface SendResultLike {
  success: boolean
  warning?: string
  messageId?: string
  error?: string
}

/**
 * Ids handed back when nothing was actually sent.
 *
 * Each of these is generated by a different "not really sending" path, and the
 * send route used to strip only `simulated-`, so the other two were stored as
 * though they were real provider ids. A reminder then threaded onto nothing.
 */
const PLACEHOLDER_ID_PREFIXES = [
  "safety-test-mode-",
  "test-mode-disabled-",
  "simulated-",
  "test-",
]

/** True when this id came from a path that did not send anything. */
export function isPlaceholderMessageId(messageId: string | null | undefined): boolean {
  const id = String(messageId ?? "").trim()
  if (!id) return false
  return PLACEHOLDER_ID_PREFIXES.some(prefix => id.startsWith(prefix))
}

/**
 * What really happened, from a send result.
 *
 * A placeholder id counts as HELD even without the warning: the two signals are
 * produced by different code paths, and either one alone is enough to know that
 * no message left.
 */
export function classifySendResult(result: SendResultLike): SendOutcome {
  if (!result.success) return "FAILED"
  if (result.warning === "SENDING_DISABLED") return "HELD"
  if (isPlaceholderMessageId(result.messageId)) return "HELD"
  return "DELIVERED"
}

/** Only a real delivery may stamp an invoice SENT. */
export function marksInvoiceSent(outcome: SendOutcome): boolean {
  return outcome === "DELIVERED"
}

/**
 * The id worth storing for threading a later reminder onto, or null.
 *
 * Storing a placeholder makes the reminder reply into a thread that does not
 * exist, which reads to the client as a first contact about an overdue bill
 * they were never sent.
 */
export function threadableMessageId(messageId: string | null | undefined): string | null {
  const id = String(messageId ?? "").trim()
  if (!id || isPlaceholderMessageId(id)) return null
  return id
}

/**
 * Whether real client email is switched on, from ONE place.
 *
 * Both flags have to be on. Callers pass `getEmailConfig()`, never the raw
 * environment · Settings → Email is what an operator actually changes, and a
 * route reading env instead of the row is how sending gets paused in the UI
 * while invoices carry on being marked SENT.
 */
export function realSendingEnabled(config: {
  allowRealClientEmails?: boolean
  enableSending?: boolean
}): boolean {
  return Boolean(config.allowRealClientEmails) && Boolean(config.enableSending)
}

/** A short reason for the UI when a send was held rather than delivered. */
export function heldReason(config: {
  allowRealClientEmails?: boolean
  enableSending?: boolean
}): string {
  if (!config.enableSending) return "Sending is paused in Settings · Email."
  if (!config.allowRealClientEmails) return "Real client emails are switched off in Settings · Email."
  return "The email was not sent, so the invoice is still a draft."
}
